services:
  app:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.yarn/cache
      - /usr/src/app/.yarn/unplugged

  mongo:
    image: mongo:4.0
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

volumes:
  mongo_data: {}



